### PR TITLE
fix: Update README.md

### PR DESCRIPTION
**Pull request by inchori**

### CODE REVIEW

**Comment by gyuguen** [comment]
Is it possible to specify a path where this service can store Data when it starts, and if so, please add a guide for that as well. `${DATA_DIR}` is confusing based on this guide document alone.

**Comment by inchori** [comment]
@gyuguen Yes, the specifying a path where the data is stored is in [here](https://github.com/medibloc/panacea-dep-consumer#installation). But I add an instruction in [6a2e877](https://github.com/medibloc/panacea-dep-consumer/pull/3/commits/6a2e8779d23e15328f8c7270906a486eedccd750).

**Review by gyuguen — APPROVED** [review]
LGTM

**Review by youngjoon-lee — APPROVED** [review]
lgtm

**Pull request merged**
